---
apiVersion: v1
kind: Template
metadata:
  name: migration-assessment
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: migration-assessment
    spec:
      API:
        versions:
          - v1
      envName: ${ENV_NAME}
      title: Assisted Migration
      deploymentRepo: https://github.com/kubev2v/migration-planner-ui-app
      frontend:
        paths:
          - /apps/assisted-migration-app
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/assisted-migration-app/fed-mods.json'
        modules:
          - id: 'migration-assessment'
            module: './RootApp'
            routes:
              - pathname: /openshift/migration-assessment

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
  - name: IMAGE
    required: true
