name: Sync Release Branch

on:
  push:
    branches:
      - master
      - stable

permissions:
  contents: write

jobs:
  sync:
    name: Sync Release Branch
    uses: kubev2v/migration-planner-workflows/.github/workflows/sync-release-branch.yml@028c8ceddf58ae8f146406aa8f363dec06438c4f # main
    secrets: inherit
