name: Sync Release Branch

on:
  push:
    branches:
      - master
      - stable

permissions:
  contents: write

jobs:
  sync:
    name: Sync Release Branch
    uses: kubev2v/migration-planner-workflows/.github/workflows/sync-release-branch.yml@706ce577094f2687205b5f9c79b952c87dbb48fc # main
    secrets: inherit
