name: Sync Release Branch

on:
  push:
    branches:
      - master
      - stable

permissions:
  contents: write

jobs:
  sync:
    name: Sync Release Branch
    uses: kubev2v/migration-planner-workflows/.github/workflows/sync-release-branch.yml@68d7dd74dac22203147eb70afd6da7bc906cc2cf # main
    secrets: inherit
